import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  { Toaster } from 'react-hot-toast';
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { LoginProvider } from "./context/LoginContext";
const Header = dynamic(()=>import('@/components/Header'))
const Footer = dynamic(()=>import('@/components/Footer'))
  


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cook Ford",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet"/>
      </head>

      <body className={inter.className}>
        <Toaster/>
        <LoginProvider>
          <StoreProvider>
          <Header/>
          {children}
          <Footer/>
          </StoreProvider>
          </LoginProvider>
      </body>
    </html>
  );
}
