import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    isLoading: true,
    data: {} ,
};

const profileDetailSlice = createSlice({
    name: 'profileDetails',
    initialState,
    reducers: {
        setProfilesdata: (state, action) => {
            state.isLoading = false;
            state.data = action.payload;
        }
    }
});

// Export the action creators generated by createSlice
export const { setProfilesdata } = profileDetailSlice.actions;

// Export the reducer generated by createSlice
export default profileDetailSlice.reducer;
