import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    isLoading: true,
    data: [] ,
};

const profileSlice = createSlice({
    name: 'profiles',
    initialState,
    reducers: {
        setProfiles: (state, action) => {
            state.isLoading = false;
            state.data = action.payload;
        }
    }
});

// Export the action creators generated by createSlice
export const { setProfiles } = profileSlice.actions;

// Export the reducer generated by createSlice
export default profileSlice.reducer;
